# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automatic_photos_taker.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_automatic_photos_taker(object):
    def setupUi(self, automatic_photos_taker):
        automatic_photos_taker.setObjectName("automatic_photos_taker")
        automatic_photos_taker.resize(650, 700)
        automatic_photos_taker.setMinimumSize(QtCore.QSize(650, 700))
        automatic_photos_taker.setMaximumSize(QtCore.QSize(650, 700))
        automatic_photos_taker.setStyleSheet("QWidget {\n"
                                             "    background-color: rgb(46, 46, 46);\n"
                                             "}")
        self.Automatic_photos_taker_label = QtWidgets.QLabel(
            automatic_photos_taker)
        self.Automatic_photos_taker_label.setGeometry(
            QtCore.QRect(225, 5, 200, 50))
        self.Automatic_photos_taker_label.setMinimumSize(QtCore.QSize(200, 50))
        self.Automatic_photos_taker_label.setMaximumSize(QtCore.QSize(200, 50))
        self.Automatic_photos_taker_label.setStyleSheet("QLabel {\n"
                                                        "    color: #ffffff;\n"
                                                        "    background-color: none;\n"
                                                        "    border: 2px solid rgb(11, 170, 22);\n"
                                                        "    border-radius: 10px;\n"
                                                        "    font-size: 13px;\n"
                                                        # "    justify-content: center;\n"
                                                        "}")
        self.Automatic_photos_taker_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Automatic_photos_taker_label.setObjectName(
            "Automatic_photos_taker_label")
        self.status_label = QtWidgets.QLabel(automatic_photos_taker)
        self.status_label.setGeometry(QtCore.QRect(225, 630, 200, 20))
        self.status_label.setMinimumSize(QtCore.QSize(200, 20))
        self.status_label.setMaximumSize(QtCore.QSize(200, 20))
        self.status_label.setStyleSheet("QLabel {\n"
                                        "    color: #ffffff;\n"
                                        "    background-color: none;\n"
                                        "    border: 2px solid rgb(255, 170, 0);\n"
                                        "    border-radius: 10px;\n"
                                        "    font-size: 13px;\n"
                                        "}")
        self.status_label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.status_label.setObjectName("status_label")
        self.process_data_btn = QtWidgets.QPushButton(automatic_photos_taker)
        self.process_data_btn.setGeometry(QtCore.QRect(225, 670, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.process_data_btn.sizePolicy().hasHeightForWidth())
        self.process_data_btn.setSizePolicy(sizePolicy)
        self.process_data_btn.setMinimumSize(QtCore.QSize(200, 20))
        self.process_data_btn.setMaximumSize(QtCore.QSize(200, 20))
        self.process_data_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.process_data_btn.setStyleSheet("QPushButton {\n"
                                            "    color: #ffffff;\n"
                                            "    background-color: none;\n"
                                            "    border: 2px solid rgb(0, 170, 255);\n"
                                            "    border-radius: 10px;\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    border: 2px solid rgb(255, 0, 0);\n"
                                            "}\n"
                                            "QPushButton:pressed {\n"
                                            "    background-color: rgb(100, 100, 100);\n"
                                            "}")
        self.process_data_btn.setCheckable(False)
        self.process_data_btn.setObjectName("process_data_btn")
        self.widget = QtWidgets.QWidget(automatic_photos_taker)
        self.widget.setGeometry(QtCore.QRect(2, 60, 650, 563))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_container_label = QtWidgets.QLabel(self.widget)
        self.image_container_label.setMinimumSize(QtCore.QSize(648, 480))
        self.image_container_label.setMaximumSize(QtCore.QSize(648, 480))
        self.image_container_label.setStyleSheet("QLabel {\n"
                                                 "    color: #ffffff;\n"
                                                 "    background-color: none;\n"
                                                 "    border: 5px solid rgb(255, 170, 0);\n"
                                                 "    font-size: 13px;\n"
                                                 "}")
        self.image_container_label.setText("")
        self.image_container_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_container_label.setObjectName("image_container_label")
        self.verticalLayout.addWidget(self.image_container_label)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox.setMaximumSize(QtCore.QSize(100, 20))
        self.comboBox.setStyleSheet("QComboBox {\n"
                                    "    background-color: rgb(46, 46, 46);\n"
                                    "    color: #ffffff;\n"
                                    "    border: 2px solid rgb(170, 0, 255);\n"
                                    "    border-radius: 10px;\n"
                                    "}\n"
                                    "QComboBox:hover {\n"
                                    "    border: 2px solid rgb(255, 0, 0);\n"
                                    "}\n"
                                    "QComboBox::drop-down {\n"
                                    "    border-top-right-radius: 3px;\n"
                                    "    border-bottom-right-radius: 3px;\n"
                                    "}\n"
                                    "QComboBox QAbstractItemView {\n"
                                    "    color: #ffffff;\n"
                                    "    selection-background-color: rgb(100, 100, 100);\n"
                                    "}\n"
                                    "\n"
                                    "")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox, 0, QtCore.Qt.AlignHCenter)
        self.start_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        self.start_btn.setMinimumSize(QtCore.QSize(50, 20))
        self.start_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.start_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.start_btn.setStyleSheet("QPushButton {\n"
                                     "    color: #ffffff;\n"
                                     "    background-color: none;\n"
                                     "    border: 2px solid rgb(0, 170, 255);\n"
                                     "    border-radius: 10px;\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    border: 2px solid rgb(255, 0, 0);\n"
                                     "}\n"
                                     "QPushButton:pressed {\n"
                                     "    background-color: rgb(100, 100, 100);\n"
                                     "}")
        self.start_btn.setCheckable(False)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout.addWidget(
            self.start_btn, 0, QtCore.Qt.AlignHCenter)
        self.stop_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.stop_btn.sizePolicy().hasHeightForWidth())
        self.stop_btn.setSizePolicy(sizePolicy)
        self.stop_btn.setMinimumSize(QtCore.QSize(50, 20))
        self.stop_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.stop_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stop_btn.setStyleSheet("QPushButton {\n"
                                    "    color: #ffffff;\n"
                                    "    background-color: none;\n"
                                    "    border: 2px solid rgb(0, 170, 255);\n"
                                    "    border-radius: 10px;\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    border: 2px solid rgb(255, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:pressed {\n"
                                    "    background-color: rgb(100, 100, 100);\n"
                                    "}")
        self.stop_btn.setCheckable(False)
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout.addWidget(self.stop_btn, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(automatic_photos_taker)
        QtCore.QMetaObject.connectSlotsByName(automatic_photos_taker)

    def retranslateUi(self, automatic_photos_taker):
        _translate = QtCore.QCoreApplication.translate
        automatic_photos_taker.setWindowTitle(_translate(
            "automatic_photos_taker", "Automatic photos taker"))
        self.Automatic_photos_taker_label.setText(_translate(
            "automatic_photos_taker", "Automatic Photos Taker"))
        self.status_label.setText(_translate(
            "automatic_photos_taker", "Current Status: Not Running !"))
        self.process_data_btn.setText(_translate(
            "automatic_photos_taker", "Process Data"))
        self.start_btn.setText(_translate("automatic_photos_taker", "Start"))
        self.stop_btn.setText(_translate("automatic_photos_taker", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    automatic_photos_taker = QtWidgets.QWidget()
    ui = Ui_automatic_photos_taker()
    ui.setupUi(automatic_photos_taker)
    automatic_photos_taker.show()
    sys.exit(app.exec_())
