# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configuration_window(object):
    def setupUi(self, Configuration_window):
        Configuration_window.setObjectName("Configuration_window")
        Configuration_window.resize(400, 400)
        Configuration_window.setMinimumSize(QtCore.QSize(400, 400))
        Configuration_window.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(Configuration_window)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget.setStyleSheet("QWidget {\n"
                                         "    background-color: rgb(46, 46, 46);\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 388, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.working_directory_label = QtWidgets.QLabel(self.layoutWidget)
        self.working_directory_label.setMinimumSize(QtCore.QSize(200, 50))
        self.working_directory_label.setMaximumSize(QtCore.QSize(200, 50))
        self.working_directory_label.setStyleSheet("QLabel {\n"
                                                   "    color: #ffffff;\n"
                                                   "    background-color: none;\n"
                                                   "    border: 2px solid rgb(11, 170, 22);\n"
                                                   "    border-radius: 10px;\n"
                                                   "    font-size: 13px;\n"
                                                   #    "    justify-content: center;\n"
                                                   "}")
        self.working_directory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.working_directory_label.setObjectName("working_directory_label")
        self.verticalLayout_2.addWidget(
            self.working_directory_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(
            QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_working_directory_path_lineEdit = QtWidgets.QLineEdit(
            self.layoutWidget)
        self.select_working_directory_path_lineEdit.setStyleSheet("QLineEdit {\n"
                                                                  "    background-color: none;\n"
                                                                  "    color: #000000;\n"
                                                                  "    border: 2px solid rgb(170, 85, 255);\n"
                                                                  "}")
        self.select_working_directory_path_lineEdit.setInputMask("")
        self.select_working_directory_path_lineEdit.setText("")
        self.select_working_directory_path_lineEdit.setMaxLength(32767)
        self.select_working_directory_path_lineEdit.setObjectName(
            "select_working_directory_path_lineEdit")
        self.horizontalLayout.addWidget(
            self.select_working_directory_path_lineEdit)
        self.browse_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.browse_btn.setMinimumSize(QtCore.QSize(50, 20))
        self.browse_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.browse_btn.setStyleSheet("QPushButton {\n"
                                      "    color: #ffffff;\n"
                                      "    background-color: none;\n"
                                      "    border: 2px solid rgb(0, 170, 255);\n"
                                      "    border-radius: 10px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    border: 2px solid rgb(255, 0, 0);\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(100, 100, 100);\n"
                                      "}")
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout.addWidget(
            self.browse_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.datasets_generation_label = QtWidgets.QLabel(self.layoutWidget)
        self.datasets_generation_label.setEnabled(True)
        self.datasets_generation_label.setMinimumSize(QtCore.QSize(200, 50))
        self.datasets_generation_label.setMaximumSize(QtCore.QSize(200, 50))
        self.datasets_generation_label.setStyleSheet("QLabel {\n"
                                                     "    color: #ffffff;\n"
                                                     "    background-color: none;\n"
                                                     "    border: 2px solid rgb(11, 170, 22);\n"
                                                     "    border-radius: 10px;\n"
                                                     "    font-size: 13px;\n"
                                                     #  "    justify-content: center;\n"
                                                     "}")
        self.datasets_generation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.datasets_generation_label.setObjectName(
            "datasets_generation_label")
        self.verticalLayout_2.addWidget(
            self.datasets_generation_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ask_user_label = QtWidgets.QLabel(self.layoutWidget)
        self.ask_user_label.setStyleSheet("QLabel {\n"
                                          "    color: #ffffff;\n"
                                          "    background-color: none;\n"
                                          "    border: 2px solid rgb(255, 170, 0);\n"
                                          "    border-radius: 10px;\n"
                                          "    font-size: 13px;\n"
                                          "}")
        self.ask_user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ask_user_label.setObjectName("ask_user_label")
        self.horizontalLayout_2.addWidget(
            self.ask_user_label, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setStyleSheet("QComboBox {\n"
                                    "    background-color: rgb(46, 46, 46);\n"
                                    "    color: #ffffff;\n"
                                    "    border: 2px solid rgb(170, 0, 255);\n"
                                    "    border-radius: 10px;\n"
                                    "}\n"
                                    "QComboBox:hover {\n"
                                    "    border: 2px solid rgb(255, 0, 0);\n"
                                    "}\n"
                                    "QComboBox::drop-down {\n"
                                    "    border-top-right-radius: 3px;\n"
                                    "    border-bottom-right-radius: 3px;\n"
                                    "}\n"
                                    "QComboBox QAbstractItemView {\n"
                                    "    color: #ffffff;\n"
                                    "    selection-background-color: rgb(100, 100, 100);\n"
                                    "}\n"
                                    "\n"
                                    "")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.confirmation_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.confirmation_btn.sizePolicy().hasHeightForWidth())
        self.confirmation_btn.setSizePolicy(sizePolicy)
        self.confirmation_btn.setMinimumSize(QtCore.QSize(200, 20))
        self.confirmation_btn.setMaximumSize(QtCore.QSize(200, 20))
        self.confirmation_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.confirmation_btn.setStyleSheet("QPushButton {\n"
                                            "    color: #ffffff;\n"
                                            "    background-color: none;\n"
                                            "    border: 2px solid rgb(0, 170, 255);\n"
                                            "    border-radius: 10px;\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    border: 2px solid rgb(255, 0, 0);\n"
                                            "}\n"
                                            "QPushButton:pressed {\n"
                                            "    background-color: rgb(100, 100, 100);\n"
                                            "}")
        self.confirmation_btn.setCheckable(False)
        self.confirmation_btn.setObjectName("confirmation_btn")
        self.verticalLayout_2.addWidget(
            self.confirmation_btn, 0, QtCore.Qt.AlignHCenter)
        Configuration_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Configuration_window)
        QtCore.QMetaObject.connectSlotsByName(Configuration_window)

    def retranslateUi(self, Configuration_window):
        _translate = QtCore.QCoreApplication.translate
        Configuration_window.setWindowTitle(_translate(
            "Configuration_window", "FaceRecognizer-Configuration"))
        self.working_directory_label.setText(_translate(
            "Configuration_window", "Working directory"))
        self.select_working_directory_path_lineEdit.setPlaceholderText(
            _translate("Configuration_window", "Select your working directory"))
        self.browse_btn.setText(_translate("Configuration_window", "Browse"))
        self.datasets_generation_label.setText(_translate(
            "Configuration_window", "Datasets Generation"))
        self.ask_user_label.setText(_translate(
            "Configuration_window", "Generate new datasets and take new photos ?"))
        self.comboBox.setItemText(0, _translate("Configuration_window", "Yes"))
        self.comboBox.setItemText(1, _translate("Configuration_window", "No"))
        self.confirmation_btn.setText(
            _translate("Configuration_window", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Configuration_window = QtWidgets.QMainWindow()
    ui = Ui_Configuration_window()
    ui.setupUi(Configuration_window)
    Configuration_window.show()
    sys.exit(app.exec_())
