# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\KARROUMI Nabil\Desktop\ApprendrePython\PROJECTS\FacesRecognition\face_recognizer-git\face_recognizer\raw_UIs\data_processing.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_data_processing(object):
    def setupUi(self, data_processing):
        data_processing.setObjectName("data_processing")
        data_processing.resize(1128, 665)
        self.centralwidget = QtWidgets.QWidget(data_processing)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(7, 10, 1111, 631))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.output_text = QtWidgets.QTextEdit(self.widget)
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.verticalLayout.addWidget(self.output_text)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        data_processing.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(data_processing)
        self.statusbar.setObjectName("statusbar")
        data_processing.setStatusBar(self.statusbar)

        self.retranslateUi(data_processing)
        QtCore.QMetaObject.connectSlotsByName(data_processing)

    def retranslateUi(self, data_processing):
        _translate = QtCore.QCoreApplication.translate
        data_processing.setWindowTitle(_translate(
            "data_processing", "data_processing"))
        self.pushButton.setText(_translate(
            "data_processing", "Lauch Processing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    data_processing = QtWidgets.QMainWindow()
    ui = Ui_data_processing()
    ui.setupUi(data_processing)
    data_processing.show()
    sys.exit(app.exec_())
