# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(200, 200)
        MainWindow.setMinimumSize(QtCore.QSize(200, 200))
        MainWindow.setMaximumSize(QtCore.QSize(200, 200))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
                                         "    background-color: rgb(46, 46, 46);\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.application_presentation_label = QtWidgets.QLabel(
            self.centralwidget)
        self.application_presentation_label.setStyleSheet("QLabel {\n"
                                                          "    color: #ffffff;\n"
                                                          "    background-color: none;\n"
                                                          "    border: 2px solid rgb(11, 170, 22);\n"
                                                          "    border-radius: 10px;\n"
                                                          "    font-size: 13px;\n"
                                                          "}")
        self.application_presentation_label.setTextFormat(QtCore.Qt.PlainText)
        self.application_presentation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.application_presentation_label.setObjectName(
            "application_presentation_label")
        self.verticalLayout.addWidget(self.application_presentation_label)
        self.application_start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.application_start_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.application_start_btn.setMaximumSize(QtCore.QSize(200, 20))
        self.application_start_btn.setStyleSheet("QPushButton {\n"
                                                 "    color: #ffffff;\n"
                                                 "    background-color: none;\n"
                                                 "    border: 2px solid rgb(0, 170, 255);\n"
                                                 "    border-radius: 10px;\n"
                                                 "}\n"
                                                 "QPushButton:hover {\n"
                                                 "    border: 2px solid rgb(255, 0, 0);\n"
                                                 "}\n"
                                                 "QPushButton:pressed {\n"
                                                 "    background-color: rgb(100, 100, 100);\n"
                                                 "}")
        self.application_start_btn.setObjectName("application_start_btn")
        self.verticalLayout.addWidget(self.application_start_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "FaceRecognizer-Presentation"))
        self.application_presentation_label.setText(
            _translate("MainWindow", "Welcome to my application !"))
        self.application_start_btn.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
